/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#fefffa",
        "on-primary-container": "#516d00",
        "surface-tint": "#a2d800",
        "surface-container-highest": "#353535",
        "secondary-container": "#454747",
        "on-surface-variant": "#c3caad",
        "tertiary-fixed": "#6bff8f",
        "on-secondary-container": "#b4b5b5",
        "surface-dim": "#131313",
        "on-tertiary-container": "#007432",
        "inverse-primary": "#4c6700",
        "on-primary-fixed-variant": "#384e00",
        "outline-variant": "#434934",
        "primary-container": "#baf517",
        "on-tertiary": "#003915",
        background: "#131313",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-fixed": "#141f00",
        "primary-fixed-dim": "#a2d800",
        "on-secondary-fixed": "#1a1c1c",
        "error-container": "#93000a",
        "on-tertiary-fixed": "#002109",
        error: "#ffb4ab",
        "on-background": "#e2e2e2",
        "surface-variant": "#353535",
        outline: "#8d947a",
        "surface-container-high": "#2a2a2a",
        primary: "#fffeff",
        surface: "#131313",
        "surface-container": "#1f1f1f",
        "tertiary-fixed-dim": "#4ae176",
        "tertiary-container": "#6afe8f",
        "on-secondary-fixed-variant": "#454747",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#e2e2e2",
        "inverse-surface": "#e2e2e2",
        "secondary-fixed-dim": "#c6c6c7",
        "on-surface": "#e2e2e2",
        "on-secondary": "#2f3131",
        "surface-bright": "#393939",
        "primary-fixed": "#bbf618",
        "on-primary": "#263500",
        "surface-container-low": "#1b1b1b",
        secondary: "#c6c6c7",
        "inverse-on-surface": "#303030",
        "on-tertiary-fixed-variant": "#005321",
        "on-error": "#690005",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        base: "8px",
        gutter: "16px",
        "margin-mobile": "20px",
        xl: "64px",
        md: "24px",
        lg: "40px",
        xs: "4px",
        "margin-desktop": "120px",
      },
      fontFamily: {
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-bold": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Anybody", "sans-serif"],
        "headline-lg-mobile": ["Anybody", "sans-serif"],
        "display-lg": ["Anybody", "sans-serif"],
        "headline-lg": ["Anybody", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-bold": [
          "14px",
          { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "700" },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
